---

language: python
python: "3.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip3 install ansible
script:
  - ansible --version | grep "python version"
  - echo localhost > inventory
  - ln -s ansible-logrotate ../buluma.logrotate
  - ansible-playbook --syntax-check -i inventory test.yml
#  - ansible-playbook -i inventory test.yml --connection=local --sudo -vvvv
  - ansible-playbook -i inventory test.yml --connection=local -vvvv

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
notifications:
  webhooks: 
    https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: always
    on_failure: always
    rooms:
      - buluma:QWpyLHvuvJe5aduZtGs7euUa#travis-ci
  email:
    recipients:
      - me@buluma.co.ke
    on_success: always # default: change
    on_failure: always # default: always
